package main

import (
	_ "backend/Config"
	"backend/Databases"
	"backend/Router"
	_ "backend/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Ackerman Blog
// @version 1.0
// @description Ackerman Blog Api Documents
// @termsOfService http://swagger.io/terms/

// @contact.name Ackerman
// @contact.url www.withrjp.xyz
// @contact.email withrjp@gmail.com

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath
func main() {
	defer Databases.Mysql.Close()
	Router.InitRouter()
}
